import type { BlackjackRules } from './rules.types';

export const vegasRules: BlackjackRules = {
  deckCount: 6,
  cutCardRatio: 0.75,
  dealerStandsOn: 17,
  dealerHitsSoft17: true,
  doubleAfterSplit: true,
  doubleOnAnyTwo: true,
  maxSplitHands: 4,
  splitAces: true,
  hitSplitAces: false,
  surrenderAllowed: true,
  lateSurrender: true,
  blackjackPayout: 1.5,
  insurancePayout: 2.0,
  minBet: 5,
  maxBet: 500,
};

export const atlanticCityRules: BlackjackRules = {
  deckCount: 8,
  cutCardRatio: 0.75,
  dealerStandsOn: 17,
  dealerHitsSoft17: false,
  doubleAfterSplit: true,
  doubleOnAnyTwo: true,
  maxSplitHands: 4,
  splitAces: true,
  hitSplitAces: false,
  surrenderAllowed: true,
  lateSurrender: true,
  blackjackPayout: 1.5,
  insurancePayout: 2.0,
  minBet: 10,
  maxBet: 1000,
};

export const europeanRules: BlackjackRules = {
  deckCount: 6,
  cutCardRatio: 0.75,
  dealerStandsOn: 17,
  dealerHitsSoft17: false,
  doubleAfterSplit: false,
  doubleOnAnyTwo: false,
  maxSplitHands: 3,
  splitAces: true,
  hitSplitAces: false,
  surrenderAllowed: false,
  lateSurrender: false,
  blackjackPayout: 1.5,
  insurancePayout: 2.0,
  minBet: 5,
  maxBet: 200,
};

export const strictRules: BlackjackRules = {
  deckCount: 8,
  cutCardRatio: 0.5,
  dealerStandsOn: 17,
  dealerHitsSoft17: true,
  doubleAfterSplit: false,
  doubleOnAnyTwo: false,
  maxSplitHands: 1,
  splitAces: false,
  hitSplitAces: false,
  surrenderAllowed: false,
  lateSurrender: false,
  blackjackPayout: 1.2,
  insurancePayout: 2.0,
  minBet: 10,
  maxBet: 100,
};

export const liberalRules: BlackjackRules = {
  deckCount: 2,
  cutCardRatio: 0.9,
  dealerStandsOn: 17,
  dealerHitsSoft17: false,
  doubleAfterSplit: true,
  doubleOnAnyTwo: true,
  maxSplitHands: 4,
  splitAces: true,
  hitSplitAces: true,
  surrenderAllowed: true,
  lateSurrender: true,
  blackjackPayout: 2.0,
  insurancePayout: 2.5,
  minBet: 1,
  maxBet: 10000,
};